  #server:
  #  servlet:
  #    context-path: /store
  #  port: 8189
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#server:
#  servlet:
#    context-path: /app
#  port: 8189
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hiber
#    username: postgres
#    password: qwe
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
#  flyway:
#    baseline-on-migrate: true